default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: webpages_development

test:
  <<: *default
  database: webpages_test

production:
  <<: *default
  database: webpages_production
  username: webpages
  password: <%= ENV['WEBPAGES_DATABASE_PASSWORD'] %>
